version: "{build}"

shallow_clone: true

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C ..\\misc\\run_with_compiler.cmd"
    OPENSSL_VER: 1.0.2d
    VS_VERSION: "2015"

  #matrix:
  #- PLAT: x86
  #  LINKAGE: static
  #
  #- PLAT: x64
  #  LINKAGE: static
  #
  #- PLAT: x86
  #  LINKAGE: shared
  #
  #- PLAT: x64
  #  LINKAGE: shared

#configuration:
#  - release
#  - debug

install:
  - C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P p7zip
  - appveyor DownloadFile ftp://ftp.openssl.org/source/openssl-%OPENSSL_VER%.tar.gz
  - appveyor DownloadFile http://www.npcglib.org/~stathis/downloads/build-openssl-%OPENSSL_VER%.bat
  - appveyor DownloadFile http://www.npcglib.org/~stathis/downloads/openssl-%OPENSSL_VER%.patch
  - 7z x openssl-%OPENSSL_VER%.tar.gz
  - 7z x openssl-%OPENSSL_VER%.tar
  - cd openssl-%OPENSSL_VER%
  - patch -p1 < ..\openssl-%OPENSSL_VER%.patch
  - cd ..
  - patch -p0 < build-script.patch

build_script:
  #- build-openssl-%OPENSSL_VER%.bat build %PLAT% %LINKAGE% %CONFIGURATION%
  #- build-openssl-%OPENSSL_VER%.bat package %PLAT% %LINKAGE%
  - build-openssl-%OPENSSL_VER%.bat build all
  - build-openssl-%OPENSSL_VER%.bat package all
  - dir /S *.7z

test: off

artifacts:
  - path: openssl-%OPENSSL_VER%-vs2015.7z
